"""empty message

Revision ID: 1adad11699ce
Revises: 7f79d84c10bb
Create Date: 2020-04-25 17:16:38.341354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adad11699ce'
down_revision = '7f79d84c10bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###
