"""empty message

Revision ID: 775f34614fdd
Revises: e27ac4c5e9ff
Create Date: 2020-04-25 14:31:49.565543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '775f34614fdd'
down_revision = 'e27ac4c5e9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'past_shows')
    op.drop_column('Artist', 'genres')
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('past_shows', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('past_shows', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
