"""empty message

Revision ID: 7f79d84c10bb
Revises: 2dcf50284e13
Create Date: 2020-04-25 17:00:09.660125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f79d84c10bb'
down_revision = '2dcf50284e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', postgresql.ARRAY(postgresql.BYTEA()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
