"""empty message

Revision ID: 86d5ac3ccfe1
Revises: 775f34614fdd
Create Date: 2020-04-25 14:34:26.670094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d5ac3ccfe1'
down_revision = '775f34614fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Artist', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Artist', 'past_shows')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
