"""empty message

Revision ID: ab73e8f30f20
Revises: 4ba863b67f94
Create Date: 2020-04-25 14:19:35.386336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab73e8f30f20'
down_revision = '4ba863b67f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
